AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ClusterName: {Type: String}
  ServiceName: {Type: String}
Resources:
  ScalableTarget:
    Type: 'AWS::ApplicationAutoScaling::ScalableTarget'
    Properties:
      MaxCapacity: 10
      MinCapacity: 2
      ResourceId: !Sub 'service/${ClusterName}/${ServiceName}'
      ScalableDimension: 'ecs:service:DesiredCount'
      ServiceNamespace: ecs
  ScalingPolicy:
    Type: 'AWS::ApplicationAutoScaling::ScalingPolicy'
    Properties:
      PolicyName: ECSTargetTrackingCPU
      PolicyType: TargetTrackingScaling
      ScalingTargetId: !Ref ScalableTarget
      TargetTrackingScalingPolicyConfiguration:
        PredefinedMetricSpecification: {PredefinedMetricType: ECSServiceAverageCPUUtilization}
        TargetValue: 70.0
        ScaleInCooldown: 60
        ScaleOutCooldown: 60
