AWSTemplateFormatVersion: '2010-09-09'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties: {CidrBlock: 10.0.0.0/16}
  Subnet1:
    Type: 'AWS::EC2::Subnet'
    Properties: {VpcId: !Ref VPC, CidrBlock: 10.0.1.0/24, AvailabilityZone: us-east-1a}
  Subnet2:
    Type: 'AWS::EC2::Subnet'
    Properties: {VpcId: !Ref VPC, CidrBlock: 10.0.2.0/24, AvailabilityZone: us-east-1b}
  ECSTaskSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow HTTP
      VpcId: !Ref VPC
      SecurityGroupIngress: [{IpProtocol: tcp, FromPort: 80, ToPort: 80, CidrIp: 0.0.0.0/0}]
  ECRRepository:
    Type: 'AWS::ECR::Repository'
    Properties: {RepositoryName: my-web-app}
